### PR TITLE
tutorial mathcomp-2

### PR DESCRIPTION
**Pull request by affeldt-aist**

### CODE REVIEW

**Comment by chdoc** [comment]
Thank you! What is the relationship between this repository and the tutorial for MathComp?

**Comment by affeldt-aist** [comment]
This is the example we used in https://github.com/math-comp/math-comp/blob/master/etc/porting_to_mathcomp2/porting.pdf

**Comment by affeldt-aist** [comment]
This document should contain a direct link to this commit...

**Comment by palmskog** [comment]
@chdoc since you are busy with other work these days, could you give me a mandate to perform some basic maintenance for this project like for Graph Theory? Most directly, merging this PR and doing basic tagging to ensure some version exists for latest Coq/MathComp?

**Comment by palmskog** [comment]
@chdoc another ping here, OK with you if I rebase this PR and merge it?

**Comment by chdoc** [comment]
> @chdoc another ping here, OK with you if I rebase this PR and merge it?

My understanding is that this will drop compatibility with MC-1.x, so I don't know. Honestly, I haven't kept up with HB / MathComp-2 adoption. If everybody is now using HB/MC-2, I suppose is fine to tie this project to HB. 

However, I don't even know when was the last time that CI ran on this project. I would like to be assured that there exists *some* version of Coq and MC that this compiles with. If it is a recent version, I would consider this a bonus.

**Pull request merged**
